a.out : add.o divide.o multifly.o substract.o main.o
	gcc -o a.out add.o divide.o multifly.o substract.o main.o
add.o : add.c
	gcc -c add.c
divide.o : divide.c
	gcc -c divide.c
multifly.o : multifly.c
	gcc -c multifly.c
substract.o : substract.c
	gcc -c substract.c
main.o : main.c
	gcc -c main.c
clean:
	rm -f a.out add.o divide.o multifly.o substract.o main.o

dummy:

